---
title: "Reading Data from Web"
author: "Mari Sanders"
date: "2024-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
```


```{r}
url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html <- read_html(url)
```


**Get the pieces we need**

```{r}
marj_use_df <- 
  drug_use_html %>% 
  html_table() %>%
  first() %>%  
  slice(-1)
```

Use `nth()` function to select the nth table from an html 

```{r}
cost_living_ny <- 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>% 
  html_table(header = TRUE) %>% 
  first()
```


```{r}
swm_url <- "https://www.imdb.com/list/ls070150896/"
swm_html <- read_html(swm_url)
```

```{r}
title_vec <- 
  swm_html %>% 
  html_elements(".ipc-title-link-wrapper .ipc-title__text") %>% 
  html_text()

runtime_vec <- 
  swm_html %>% 
  html_elements(".dli-title-metadata-item:nth-child(2)") %>% 
  html_text()

score_vec <- 
  swm_html %>% 
  html_elements(".metacritic-score-box") %>% 
  html_text()

swm_df <- tibble(
  title = title_vec, 
  runtime = runtime_vec, 
  score = score_vec
)
```


```{r}

books_html <- read_html("https://books.toscrape.com/")

books_html %>% 
  html_elements(".product_pod a") %>% 
  html_text()

books_html %>% 
  html_elements(".price_color") %>% 
  html_text()
```

## Use API


```{r}
nyc_water <- 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content()
```


**BRFSS Data**

```{r}
brfss_data <- 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv", 
      query = list("$limit" = 5000)) %>% 
  content()
```


**Pokemon API**

```{r}
pokemon <- 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") %>%  
  content()

pokemon$height
pokemon$abilities
```

